### ISSUE TITLE
LD Scores for concatenation must have identical SNP columns.

### ISSUE THREAD

**Issue by C0nc** [kkdey/GSSG#30]
Sorry, but the snp number in the baselineLD_v2.1_annots download from the Google Cloud can not match the one generated by the user.

ValueError: LD Scores for concatenation must have identical SNP columns.

and I encountered this problem when following the command the reproduce the article results in the final run_ldsc_reg.sh process

**Comment by SidSouthekal-Lilly** [comment]
@C0nc  I am getting the same error, were you able to resolve it?
Also tried switching to previous ldsc commit and different baseline version files.

Call: 
./ldsc.py \
--h2 SUMSTATS_PATH/UKB_460K.biochemistry_Glucose.sumstats \
--ref-ld-chr sclinker_Annots/sclinker_DiseaseProgram /Disease_Innate.lymphoid.cell/ABC_Road_FAT/ABC_Road_FAT.,LDSC_PATH/baselineLD_v2.1_annots/baselineLD. \
--out sclinker_out/baselineLD_v2.1_annots/sclinker_DiseaseProgram /Disease_Innate.lymphoid.cell/ABC_Road_FAT/UKB_460K.biochemistry_Glucose.sumstats \
--overlap-annot  \
--frqfile-chr LDSC_PATH/1000G_Phase3_frq/1000G.EUR.QC. \
--w-ld-chr LDSC_PATH/weights_hm3_no_hla. \
--print-coefficients  \
--print-delete-vals  

Beginning analysis at Mon Mar 11 11:27:57 2024
Reading summary statistics from SUMSTATS_PATH/UKB_460K.biochemistry_Glucose.sumstats ...
Read summary statistics for 1187344 SNPs.
Reading reference panel LD Score from sclinker_Annots/sclinker_DiseaseProgram/Disease_Innate.lymphoid.cell/ABC_Road_FAT/ABC_Road_FAT.,LDSC_PATH/baselineLD_v2.1_annots/baselineLD.[1-22] ...
Error parsing reference panel LD Score.
Traceback (most recent call last):
  File " /ldsc/ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File " /ldsc/ldscore/sumstats.py", line 326, in estimate_h2
    args, log, args.h2)
  File "/ldsc/ldscore/sumstats.py", line 243, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/ldsc/ldscore/sumstats.py", line 82, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/ldsc/ldscore/sumstats.py", line 155, in _read_chr_split_files
    raise e
ValueError: LD Scores for concatenation must have identical SNP columns.
